version: "3.9"
networks:
  internal:
    driver: bridge
    
volumes:
  pg_data:

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db_setup:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    networks:
      - internal
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=qwerty
    networks:
      - internal
    depends_on:
      - postgres
   