version: "3.9"
networks:
  internal:
    driver: bridge
    
volumes:
  pg_data:
  redis_data:

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=qwerty
    networks:
      - internal
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=qwerty
    networks:
      - internal
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - mail-sender

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal

  mail-sender:
    image: bbaktyke/beka:latest
    restart: always
    ports:
      - "8081:8081"
    networks:
      - internal
    depends_on:
      - rabbitmq